---
title: CodeBook
output: html_document
---

## Data description

The UCIHAR dataset was retrived from: [https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).

'The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.'[1]

[1] Description retrived from:
[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

## Data merging & cleaning

Running the script needs insetting the directory providing the raw data from the download link above. The dataset was created by merging the training and test data. This included the subject IDs the ativity labels and the actual data set. Afterwards mean and standard-deviation variables were subsetted. Then original variables were renamed to be more descriptive. The labels of the activity variable were transformed to character values, describing the actual activity. 

## Data summarizing

All variables were summarized by the average for each subject and each activity. The result is saved as 'meanByAcitivityandIDSummary.txt'.

## Result dataset
The 'meanByAcitivityandIDSummary.txt' contains the following variables. It therfore describes for all 30 subjects every activity per average. So it consists of 180 measures.

First column of the datasets is the subject id (ranges from 1-30). Second column is the activity as character variable coding the six activites (walking, walkingUp, walkingDown, sitting, standing, laying). The following variables are coded by their variable name. First word descripes time or frequency measure. Its followed by Body or Gravity mode of device. Jerk abbrevation codes the Jerk signal which is transformed to Euclidian norm in the Mag variables. One half of the variables are means and the other half are standard devations (mean, std). Last is the recorded axial (x,y,z). 

